# Generated by Django 5.1.2 on 2024-10-21 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('advisor', models.CharField(max_length=255)),
                ('co_advisor', models.CharField(blank=True, max_length=255, null=True)),
                ('year', models.IntegerField()),
                ('category', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('pdf', models.FileField(upload_to='theses/')),
                ('visible', models.BooleanField(default=True)),
            ],
        ),
    ]
