# Generated by Django 5.1.2 on 2024-10-22 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesis', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='uploaded_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='thesis',
            name='category',
            field=models.CharField(choices=[('programacion', 'Programación'), ('redes', 'Redes'), ('seguridad', 'Seguridad'), ('iot', 'IoT'), ('big_data', 'Big Data'), ('inteligencia_artificial', 'Inteligencia Artificial')], max_length=50),
        ),
    ]
